# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-07-15 00:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('academic_year', models.IntegerField()),
                ('semester', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Learning Management System',
                'verbose_name_plural': 'Learning Management Systems',
            },
        ),
        migrations.CreateModel(
            name='LMS_Web_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_service_name', models.CharField(max_length=128)),
                ('web_service_method', models.CharField(max_length=128)),
                ('web_service_url', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'LMS Web Service',
                'verbose_name_plural': 'LMS Web Services',
            },
        ),
        migrations.CreateModel(
            name='My_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.LMS')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('my_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='foraliving.My_User')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.LMS')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Video_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=128)),
                ('my_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commenter', to='foraliving.My_User')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='foraliving.Video')),
            ],
        ),
        migrations.AddField(
            model_name='my_user',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.School'),
        ),
        migrations.AddField(
            model_name='my_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='my_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Professional', to='foraliving.My_User'),
        ),
        migrations.AddField(
            model_name='class',
            name='lms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.LMS'),
        ),
        migrations.AddField(
            model_name='class',
            name='my_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher', to='foraliving.My_User'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.School'),
        ),
        migrations.AddField(
            model_name='answer',
            name='my_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Provided By+', to='foraliving.My_User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Question'),
        ),
    ]
