# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-07-25 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lms',
            options={'verbose_name': 'LMS', 'verbose_name_plural': 'LMS'},
        ),
        migrations.AlterModelOptions(
            name='my_user',
            options={'verbose_name': 'FAL User', 'verbose_name_plural': 'FAL Users'},
        ),
        migrations.AlterModelOptions(
            name='video_comment',
            options={'verbose_name': 'Video Comment', 'verbose_name_plural': 'Video Comments'},
        ),
    ]
