# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0002_auto_20160901_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='funny', max_length=128),
            preserve_default=False,
        ),
    ]
